# 2.5 自动求导实现

In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

计算y关于x的梯度之前需要存储每一层的梯度
之后可以通过x.grad访问梯度

In [2]:
x.requires_grad_(True)
x.grad

正向计算y

In [3]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

反向传播

In [4]:
y.backward()

In [5]:
x.grad

tensor([ 0.,  4.,  8., 12.])

验证

In [6]:
x.grad == 4 * x

tensor([True, True, True, True])

清除梯度

In [7]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

将一些计算移到计算图以外

In [8]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [9]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])