In [14]:
import torch

In [15]:
# 创建数组（形状/数据类型/值）
x1 = torch.arange(12)
print(x1)
print(x1.shape)          # 访问形状
print(x1.numel())        # 访问元素个数

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12


In [16]:
# 改变元素形状
x2 = x1.reshape(3, 4)     # 这里 x2 是 x1 的一个 view，实际上还是 x1
print(x2)
print(x2.shape)
print(x2.numel())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
12


In [17]:
# 设定张量值
x3 = torch.zeros((2,3,4))       # 三维全0矩阵
x4 = torch.ones((2,3,4))        # 三维全1矩阵
x5 = torch.tensor([[1,2,3],[4,5,6]])    # 通过python列表直接赋值
print(x3)
print(x4)
print(x5)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [18]:
# 标准算数运算（按对应元素进行）
x = torch.tensor([1,2,4,8])
y = torch.tensor([2,2,2,2])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y)
print(torch.exp(x))     # e^x

tensor([ 3,  4,  6, 10])
tensor([-1,  0,  2,  6])
tensor([ 2,  4,  8, 16])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1,  4, 16, 64])
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


In [19]:
# 张量之间的运算
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0, 1,3,4],[1,2,3,4],[3,4,5,6]])
print(x)
print(y)
print(torch.cat((x,y),dim=0))   # 在第0维合并
print(torch.cat((x,y),dim=1))   # 在第1维合并
print(x==y)     # 逻辑运算构建张量
print(x.sum())  # 返回一个标量

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 3., 4.],
        [1., 2., 3., 4.],
        [3., 4., 5., 6.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  3.,  4.],
        [ 1.,  2.,  3.,  4.],
        [ 3.,  4.,  5.,  6.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  3.,  4.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  3.,  4.,  5.,  6.]])
tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor(66.)


In [20]:
# 广播机制
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a)
print(b)
print(a+b)  # 维度相同，每一维进行复制

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [21]:
# 访问元素（元素/行/列/子区域/跳转子区域）
x = torch.arange(12).reshape((3,4))
print(x)
print(x[-1])    # 选择最后一个元素
print(x[1,2])
print(x[1,:])
print(x[:,1])
print(x[1:3, 1:2])
print(x[0::2,1])
x[0:2, :] = 12  # 多元素修改
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 8,  9, 10, 11])
tensor(6)
tensor([4, 5, 6, 7])
tensor([1, 5, 9])
tensor([[5],
        [9]])
tensor([1, 9])
tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])


In [22]:
# 内存问题
x = torch.arange(12)
y = torch.zeros(12)
y = x + y       # 新变量
y[:] = x + y    # 原地复制
y += x          # 原地复制

In [23]:
# numpy转化
x = torch.arange(12).reshape((3,4))
A = x.numpy()       # 转化为 numpy
B = torch.tensor(A) # 转化为 tensor
print(type(A))
print(type(B))

y = torch.tensor([1.1])
print(y)
print(y.item())
print(float(y))
print(int(y))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
tensor([1.1000])
1.100000023841858
1.100000023841858
1
