In [2]:
import torch

#### 1 标量

In [3]:
x = torch.tensor([3.0])
print(x)

tensor([3.])


#### 2 向量

In [5]:
y1 = torch.arange(4)
y2 = torch.tensor([1,2,3,4])
print(y1)
print(y2)

print(y1[2])
print(len(y1))
print(y1.shape)

tensor([0, 1, 2, 3])
tensor([1, 2, 3, 4])
tensor(2)
4
torch.Size([4])


#### 3 矩阵

In [7]:
A = torch.arange(12).reshape(3,4)
print(A)
print(A.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


#### 4 高维张量

In [8]:
X = torch.arange(24).reshape(2,3,4)
Y = X.clone()
print(X)
print(X + Y)    # 按元素相加
print(X * Y)    # 按元素相乘（哈达玛积）

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])
tensor([[[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121]],

        [[144, 169, 196, 225],
         [256, 289, 324, 361],
         [400, 441, 484, 529]]])


#### 5 求和

In [9]:
X = torch.arange(24).reshape(2,3,4)
print(X.shape)  # 张量形状
print(X.sum())
print(X.sum(axis=0))
print(X.sum(axis=1))
print(X.sum(axis=2))
print(X.sum(axis=0, keepdims=True)) # 保持形状不降维

torch.Size([2, 3, 4])
tensor(276)
tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
tensor([[ 6, 22, 38],
        [54, 70, 86]])
tensor([[[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]])


#### 6 求均值

In [10]:
X = torch.randn(24).reshape(2,3,4)
print(X.mean())
print(X.sum() / X.numel())
print(X.mean(axis=0))
print(X.sum(axis=0) / X.shape[0])

tensor(-0.4059)
tensor(-0.4059)
tensor([[-0.4822, -0.0095, -0.8016, -1.0416],
        [ 0.2378, -0.3561,  0.3217, -0.9178],
        [-0.6444,  0.1630, -1.0322, -0.3078]])
tensor([[-0.4822, -0.0095, -0.8016, -1.0416],
        [ 0.2378, -0.3561,  0.3217, -0.9178],
        [-0.6444,  0.1630, -1.0322, -0.3078]])


#### 7 乘法

In [11]:
x = torch.arange(4.0)
y = torch.ones(4)
print(torch.dot(x,y))   # 向量点积
print(torch.sum(x * y)) # 等价于点积
A = torch.arange(20.0).reshape(5, 4)
print(torch.mv(A,x))      # 矩阵 × 向量
B = torch.arange(20.0).reshape(4, 5)
print(torch.mm(A,B))    # 矩阵 × 矩阵

tensor(6.)
tensor(6.)
tensor([ 14.,  38.,  62.,  86., 110.])
tensor([[ 70.,  76.,  82.,  88.,  94.],
        [190., 212., 234., 256., 278.],
        [310., 348., 386., 424., 462.],
        [430., 484., 538., 592., 646.],
        [550., 620., 690., 760., 830.]])


#### 8 范数

In [12]:
u = torch.tensor([3.0, -4.0])
print(torch.abs(u).sum())   # 向量的 L1 范数
print(torch.norm(u))        # 向量的 L2 范数

U = torch.ones(4, 9)
print(torch.norm(U))        # 矩阵的 F 范数

tensor(7.)
tensor(5.)
tensor(6.)
